name: leagx
description: A sports analytics app

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cached_network_image: ^3.2.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.1.6
  fluttertoast: ^8.0.9
  font_awesome_flutter: ^10.1.0
  intl: ^0.17.0
  provider: ^6.0.2
  shared_preferences: ^2.0.13
  smooth_page_indicator: ^1.0.0+2
  carousel_slider: ^4.1.1
  charts_flutter: ^0.12.0
  dio: ^4.0.6
  connectivity_plus: ^2.3.6+1
  flutter_easyloading: ^3.0.5
  twitter_login: ^4.2.3
  get_it: ^7.2.0
  pretty_dio_logger: ^1.1.1
  timeago: ^3.3.0
  image_picker: ^0.8.5+3
  image_cropper: ^3.0.0
  flutter_keyboard_visibility: ^5.3.0
  sign_in_with_apple: ^4.1.0
  flutter_stripe: ^5.1.0
  multiple_result: ^1.0.4
  awesome_dialog: ^3.0.2
  translator: ^0.1.7
  shimmer: ^2.0.0
  flame: ^1.4.0

  payments:
    path: ./packages/payments

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#111820"
  image: assets/icons/ic_splash.png
  android_12:
    color: "#111820"
    image: assets/icons/ic_splash.png

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
    - assets/images/
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-SemiBold.ttf
          weight: 600

    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
        - asset: assets/fonts/OpenSans-Regular.ttf
